/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Emin
 */
public class FacilitiesProperties extends javax.swing.JFrame {

    /**
     * Creates new form FacilitiesProperties
     */
    public FacilitiesProperties() {
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_facilities = new javax.swing.JComboBox<>();
        pnl_specs = new javax.swing.JPanel();
        lb_image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_specs = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lb_price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facility:");

        combo_facilities.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combo_facilities.setForeground(new java.awt.Color(64, 43, 100));
        combo_facilities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dining Hall", "Sport Center", "Cinema" }));
        combo_facilities.setSelectedIndex(-1);
        combo_facilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_facilitiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(combo_facilities, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_facilities)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_specs.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ta_specs.setEditable(false);
        ta_specs.setColumns(20);
        ta_specs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ta_specs.setForeground(new java.awt.Color(64, 43, 100));
        ta_specs.setRows(5);
        jScrollPane2.setViewportView(ta_specs);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 33, 89));
        jLabel2.setText("Price per Guest for a Day:");

        lb_price.setBackground(new java.awt.Color(255, 255, 255));
        lb_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_price.setForeground(new java.awt.Color(64, 43, 100));

        javax.swing.GroupLayout pnl_specsLayout = new javax.swing.GroupLayout(pnl_specs);
        pnl_specs.setLayout(pnl_specsLayout);
        pnl_specsLayout.setHorizontalGroup(
            pnl_specsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_specsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_specsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(pnl_specsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_specsLayout.setVerticalGroup(
            pnl_specsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_specsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_specsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_specs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_specs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_facilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_facilitiesActionPerformed

        int index = combo_facilities.getSelectedIndex();
        if(index>=0){
            pnl_specs.setVisible(true);
            if(index == 0){
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\diningHall.jpg"));
                Image temp = icon.getImage();
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
                DiningHall diningHall = new DiningHall();
                lb_price.setText(String.valueOf(diningHall.price()));
                ta_specs.setText(new DiningHall().contents());
                
                

            }
            else if(index == 1){
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\sportCenter.png"));
                Image temp = icon.getImage();
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
                SportCenter sportCenter = new SportCenter();
                lb_price.setText(String.valueOf(sportCenter.price()));
                ta_specs.setText(sportCenter.contents());

               
            }
            else{
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\cinema.jpg"));
                Image temp = icon.getImage();
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
                Cinema cinema = new Cinema();
                lb_price.setText(String.valueOf(cinema.price()));
                ta_specs.setText(new Cinema().contents());

            }

        }
        else
        pnl_specs.setVisible(false);

    }//GEN-LAST:event_combo_facilitiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacilitiesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacilitiesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacilitiesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacilitiesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacilitiesProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_facilities;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_price;
    private javax.swing.JPanel pnl_specs;
    private javax.swing.JTextArea ta_specs;
    // End of variables declaration//GEN-END:variables
}
