/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Login_Screen extends javax.swing.JFrame {

   ArrayList<Staff> admins = new ArrayList<Staff>();
    
    
    public Login_Screen() {
        initComponents();
       ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\username_32px.png"));    
       lb_icon_username.setIcon(icon);
       
       ImageIcon icon2 = new ImageIcon(getClass().getResource("\\images\\password_32px.png"));    
       lb_icon_password.setIcon(icon2);
       
      
        setVisible(true);
        Staff admin1 = new Staff("EminSimsek", "admin1", "Emin", "Şimşek", "Turkish", "00000000001", 21);
		admins.add(admin1);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pf_password = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        bt_login = new javax.swing.JButton();
        lb_icon_username = new javax.swing.JLabel();
        lb_icon_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Management System Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Login Screen");

        lb_username.setBackground(new java.awt.Color(204, 204, 204));
        lb_username.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_username.setForeground(new java.awt.Color(204, 204, 204));
        lb_username.setText("Username:");

        lb_password.setBackground(new java.awt.Color(204, 204, 204));
        lb_password.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_password.setForeground(new java.awt.Color(204, 204, 204));
        lb_password.setText("Password:");

        tf_username.setBackground(new java.awt.Color(36, 47, 65));
        tf_username.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tf_username.setForeground(new java.awt.Color(255, 255, 255));
        tf_username.setBorder(null);
        tf_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_username.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tf_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_usernameKeyPressed(evt);
            }
        });

        pf_password.setBackground(new java.awt.Color(36, 47, 65));
        pf_password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pf_password.setForeground(new java.awt.Color(255, 255, 255));
        pf_password.setBorder(null);
        pf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_passwordKeyPressed(evt);
            }
        });

        bt_login.setBackground(new java.awt.Color(97, 212, 195));
        bt_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("Login");
        bt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        lb_icon_username.setBackground(new java.awt.Color(255, 255, 255));
        lb_icon_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_icon_username.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_icon_username, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_username)
                .addGap(39, 39, 39)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_icon_password, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_password)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_username, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(tf_username)
                    .addComponent(lb_icon_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_icon_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
       
        
        login();
    }//GEN-LAST:event_bt_loginActionPerformed

    private void pf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_passwordKeyPressed
       int keyCode = evt.getKeyCode();
        if(keyCode == KeyEvent.VK_ENTER)
            login();
       
    }//GEN-LAST:event_pf_passwordKeyPressed

    private void tf_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usernameKeyPressed
         int keyCode = evt.getKeyCode();
          if(keyCode == KeyEvent.VK_ENTER)
            login();

    }//GEN-LAST:event_tf_usernameKeyPressed

    /**
     * @param args the command line arguments
     */
     private void login(){
            String username= tf_username.getText();
            String password = new String(pf_password.getPassword());
            String message="";
            if(username.isEmpty()||password.isEmpty()){
                if(username.isEmpty())
                    JOptionPane.showMessageDialog(this, "<html><font face='Segoe UI' size='12' color='red'>Username cannot be empty!");
                else
                    JOptionPane.showMessageDialog(this, "<html><font face='Segoe UI' size='12' color='red'>Password cannot be empty!");
                
            }
      
            
            else{
            for (int i = 0; i < admins.size(); i++) {
            if(admins.get(i).getUsername().equals(username)&&admins.get(i).getPassword().equals(password)){
                message = "Login Successful !";
                break;
            }
        
            else if(admins.get(i).getUsername().equals(username)&&!admins.get(i).getPassword().equals(password)){
                message = "Wrong Password !";
                break;
                
            }       
        }
        if(message.equals("Login Successful !")){
            JOptionPane.showMessageDialog(this, "<html><font face='Segoe UI' size='12' color='green'>"+message);
            setVisible(false);
            HomeFrame hotelFrame  = new HomeFrame();
        }
        else if(message == ""){
            message = "Wrong Username and Password !";
            JOptionPane.showMessageDialog(this, "<html><font face='Segoe UI' size='12' color='red'>"+message);
        }
        else{
            JOptionPane.showMessageDialog(this, "<html><font face='Segoe UI' size='12' color='red'>"+message);
        }
        
        
        }
            tf_username.setText("");
            pf_password.setText("");
       
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lb_icon_password;
    private javax.swing.JLabel lb_icon_username;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_username;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
