/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Emin
 */
public class RoomTypesProperties extends javax.swing.JFrame {

    /**
     * Creates new form RoomTypesProperties
     */
    public RoomTypesProperties() {
        initComponents();
        setVisible(true);
       pnl_cards_roomTypes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_roomTypes = new javax.swing.JComboBox<>();
        pnl_cards_roomTypes = new javax.swing.JPanel();
        lb_image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lb_area = new javax.swing.JLabel();
        lb_lcdTV = new javax.swing.JLabel();
        lb_balcony = new javax.swing.JLabel();
        lb_jacuzzi = new javax.swing.JLabel();
        lb_decoration = new javax.swing.JLabel();
        lb_electronicLock = new javax.swing.JLabel();
        lb_dailyMeal = new javax.swing.JLabel();
        lb_plusTicket = new javax.swing.JLabel();
        lb_privateCase = new javax.swing.JLabel();
        lb_minibar = new javax.swing.JLabel();
        lb_wifi = new javax.swing.JLabel();
        lb_capacity = new javax.swing.JLabel();
        lb_price = new javax.swing.JLabel();
        lb_dailyService = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room Type:");

        combo_roomTypes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_roomTypes.setForeground(new java.awt.Color(64, 43, 100));
        combo_roomTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic Room", "Suite Room", "King Room" }));
        combo_roomTypes.setSelectedIndex(-1);
        combo_roomTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_roomTypesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_roomTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(combo_roomTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_cards_roomTypes.setBackground(new java.awt.Color(255, 255, 255));

        lb_image.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 33, 89));
        jLabel3.setText("Room Capacity:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(54, 33, 89));
        jLabel11.setText("Room Area(m^2):");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("Price:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(54, 33, 89));
        jLabel13.setText("LCD TV:");
        jLabel13.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(54, 33, 89));
        jLabel14.setText("Electronic Door Lock:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(54, 33, 89));
        jLabel15.setText("Daily Meal:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(54, 33, 89));
        jLabel16.setText("Balcony:");
        jLabel16.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("Wifi:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(54, 33, 89));
        jLabel18.setText("Plus Ticket:");
        jLabel18.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("Daily Room Service:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(54, 33, 89));
        jLabel20.setText("Decoration:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(54, 33, 89));
        jLabel21.setText("Minibar:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(54, 33, 89));
        jLabel22.setText("Jacuzzi:");
        jLabel22.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(54, 33, 89));
        jLabel23.setText("Private Case:");

        lb_area.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_area.setForeground(new java.awt.Color(64, 43, 100));

        lb_lcdTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_lcdTV.setForeground(new java.awt.Color(64, 43, 100));

        lb_balcony.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_balcony.setForeground(new java.awt.Color(64, 43, 100));

        lb_jacuzzi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_jacuzzi.setForeground(new java.awt.Color(64, 43, 100));

        lb_decoration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_decoration.setForeground(new java.awt.Color(64, 43, 100));

        lb_electronicLock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_electronicLock.setForeground(new java.awt.Color(64, 43, 100));

        lb_dailyMeal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dailyMeal.setForeground(new java.awt.Color(64, 43, 100));

        lb_plusTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_plusTicket.setForeground(new java.awt.Color(64, 43, 100));

        lb_privateCase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_privateCase.setForeground(new java.awt.Color(64, 43, 100));

        lb_minibar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_minibar.setForeground(new java.awt.Color(64, 43, 100));

        lb_wifi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_wifi.setForeground(new java.awt.Color(64, 43, 100));

        lb_capacity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_capacity.setForeground(new java.awt.Color(64, 43, 100));

        lb_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_price.setForeground(new java.awt.Color(64, 43, 100));

        lb_dailyService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dailyService.setForeground(new java.awt.Color(64, 43, 100));
        lb_dailyService.setPreferredSize(new java.awt.Dimension(41, 16));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_dailyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lb_area, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lb_lcdTV, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_privateCase, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_decoration, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lb_minibar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lb_electronicLock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_jacuzzi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_dailyService, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_plusTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_lcdTV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_area, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_decoration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_dailyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_privateCase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_minibar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_electronicLock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_jacuzzi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dailyService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_plusTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout pnl_cards_roomTypesLayout = new javax.swing.GroupLayout(pnl_cards_roomTypes);
        pnl_cards_roomTypes.setLayout(pnl_cards_roomTypesLayout);
        pnl_cards_roomTypesLayout.setHorizontalGroup(
            pnl_cards_roomTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cards_roomTypesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_cards_roomTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_cards_roomTypesLayout.setVerticalGroup(
            pnl_cards_roomTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cards_roomTypesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_image, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_cards_roomTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_cards_roomTypes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_roomTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_roomTypesActionPerformed
  
        int index = combo_roomTypes.getSelectedIndex();
        if(index>=0){
             pnl_cards_roomTypes.setVisible(true);
            if(index == 0){
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\basicRoom.jpg"));    
                Image temp = icon.getImage();   
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);       
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
          
                setSpecs(new BasicRoom(-1));
                
            }
            else if(index == 1){
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\suitRoom.jfif"));    
                Image temp = icon.getImage();   
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);       
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
                
                setSpecs(new SuitRoom(-1));
            }
            else{
                ImageIcon icon = new ImageIcon(getClass().getResource("\\images\\kingRoom.jfif"));    
                Image temp = icon.getImage();   
                temp = temp.getScaledInstance(lb_image.getWidth(),lb_image.getHeight(),Image.SCALE_SMOOTH);       
                icon = new ImageIcon(temp);
                lb_image.setIcon(icon);
                
                setSpecs(new KingRoom(-1));
                
            }
        
        }
        else
             pnl_cards_roomTypes.setVisible(false);
        
        
        
        
        
        
    }//GEN-LAST:event_combo_roomTypesActionPerformed

    private void setSpecs(Room room){
            if(room instanceof BasicRoom){
                Room temp = new BasicRoom(-1);
                lb_price.setText(String.valueOf(temp.getRoomPrice()));
                lb_area.setText(String.valueOf(temp.calculateRoomArea()));
                lb_lcdTV.setText(String.valueOf(temp.getLcdTV()));
                lb_decoration.setText(temp.getRoomDecoration());
                lb_wifi.setText(String.valueOf(new String((temp.isWifi()) ? "Yes" : "No")));
                lb_capacity.setText(String.valueOf(temp.getRoomCapacity()));
                lb_dailyMeal.setText("No");
                lb_dailyService.setText("No");
                lb_balcony.setText("No");
                lb_privateCase.setText("No");
                lb_electronicLock.setText("No");
                lb_minibar.setText("No");
                lb_jacuzzi.setText("No");     
                lb_plusTicket.setText("No");
                
                
            }
            else if(room instanceof KingRoom){
                KingRoom temp = new KingRoom(-1);
                lb_price.setText(String.valueOf(temp.getRoomPrice()));
                lb_area.setText(String.valueOf(temp.calculateRoomArea()));
                lb_lcdTV.setText(String.valueOf(temp.getLcdTV()));
                lb_decoration.setText(temp.getRoomDecoration());
                lb_wifi.setText(String.valueOf(new String((temp.isWifi()) ? "Yes" : "No")));
                lb_capacity.setText(String.valueOf(temp.getRoomCapacity()));
                lb_dailyMeal.setText(String.valueOf(new String((temp.isDailyMeal()) ? "Yes" : "No")));
                lb_dailyService.setText(String.valueOf(new String((temp.isDailyRoomService()) ? "Yes" : "No")));
                lb_balcony.setText(String.valueOf(new String((temp.isBalcony()) ? "Yes" : "No")));
                lb_privateCase.setText(String.valueOf(new String((temp.isPrivateCase()) ? "Yes" : "No")));
                lb_electronicLock.setText(String.valueOf(new String((temp.isElectronicDoorLock()) ? "Yes" : "No")));
                lb_minibar.setText(String.valueOf(new String((temp.isMinibar()) ? "Yes" : "No")));
                lb_jacuzzi.setText(String.valueOf(new String((temp.isJacuzzi()) ? "Yes" : "No")));     
                lb_plusTicket.setText(String.valueOf(new String((temp.isPlusTicket()) ? "Yes" : "No")));
            }
            else{
                SuitRoom temp = new SuitRoom(-1);
                lb_price.setText(String.valueOf(temp.getRoomPrice()));
                lb_area.setText(String.valueOf(temp.calculateRoomArea()));
                lb_lcdTV.setText(String.valueOf(temp.getLcdTV()));
                lb_decoration.setText(temp.getRoomDecoration());
                lb_wifi.setText(String.valueOf(new String((temp.isWifi()) ? "Yes" : "No")));
                lb_capacity.setText(String.valueOf(temp.getRoomCapacity()));
                lb_dailyMeal.setText(String.valueOf(new String((temp.isDailyMeal()) ? "Yes" : "No")));
                lb_dailyService.setText(String.valueOf(new String((temp.isDailyRoomService()) ? "Yes" : "No")));
                lb_balcony.setText(String.valueOf(new String((temp.isBalcony()) ? "Yes" : "No")));
                lb_privateCase.setText(String.valueOf(new String((temp.isPrivateCase()) ? "Yes" : "No")));
                lb_electronicLock.setText("No");
                lb_minibar.setText(String.valueOf(new String((temp.isMinibar()) ? "Yes" : "No")));
                lb_jacuzzi.setText("No");     
                lb_plusTicket.setText("No");
            }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomTypesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomTypesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomTypesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomTypesProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomTypesProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_roomTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_area;
    private javax.swing.JLabel lb_balcony;
    private javax.swing.JLabel lb_capacity;
    private javax.swing.JLabel lb_dailyMeal;
    private javax.swing.JLabel lb_dailyService;
    private javax.swing.JLabel lb_decoration;
    private javax.swing.JLabel lb_electronicLock;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_jacuzzi;
    private javax.swing.JLabel lb_lcdTV;
    private javax.swing.JLabel lb_minibar;
    private javax.swing.JLabel lb_plusTicket;
    private javax.swing.JLabel lb_price;
    private javax.swing.JLabel lb_privateCase;
    private javax.swing.JLabel lb_wifi;
    private javax.swing.JPanel pnl_cards_roomTypes;
    // End of variables declaration//GEN-END:variables
}
